### ISSUE TITLE
Do not work on Node

### ISSUE THREAD

**Issue by zallek** [davidcaseria/hash-object#1]
Hi,

It doesn't seems to work on Node as it's returns the same string
![image](https://cloud.githubusercontent.com/assets/1886834/6466297/dc9c048c-c1c6-11e4-956a-b2dd766aa035.png)

But it works in RequireBin (browserify in Chrome)
![image](https://cloud.githubusercontent.com/assets/1886834/6466348/36bda416-c1c7-11e4-906d-d625eb740e91.png)

**Comment by bevacqua** [comment]
@zallek consider using `hash-sum` which has roughly the same use cases https://github.com/bevacqua/hash-sum, works in both node and the browser, minimal footprint
